### ISSUE TITLE
OpenTelemetry trace with HttpClient isn't working

### ISSUE THREAD

**Issue by BretJohnson** [BretJohnson/aspire-mobile#29]
OpenTelemetry logging works now, with the Aspire dashboard, but trace still doesn't work for HttpClient connections from the MAUI app. Need to investigate why.

**Comment by BartNetJS** [comment]
I have the same issue:

![image](https://github.com/BretJohnson/aspire-mobile/assets/4865355/7864557d-91d4-43e7-b5bc-9ca46cacdfa6)

**Comment by BretJohnson** [comment]
Fixed, with the changes here: https://github.com/BretJohnson/aspire-mobile/commit/4cbb7a0352aecb996ebb7682e341f20b0b50f12
These fixes are now published to nuget.org. Let me know if you see any other issues around OpenTelemetry.
